version: '3.9'
services:
  postgres-db:
    container_name: ${POSTGRES_HOST}
    image: postgres:9.5
    restart: always
    ports:
      - "5432:5432"
    command: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

      #this ENV variable is only required for the healthcheck section - if you don't specify it, the check command will fail stating the root user doesn't exist in posgres
      PGUSER: "postgres"
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    container_name: liquibase-schema-config
    image: company/liquibase
    build:
      context: ./liquibase
    environment:
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${POSTGRES_PORT}
      - PGHOST=${POSTGRES_HOST}
      - PGUSER=${POSTGRES_USER}
      - PGDATABASE=${POSTGRES_DB}

      - JDBC_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/
      - LIQUIBASE_HOME=${LIQUIBASE_HOME}
    depends_on:
      #CHANGE 2: it prevents issuing a request while the server is starting to depend on the healthy status of postgres-db 
      postgres-db:
        condition: service_healthy