# Generated by Django 4.2.3 on 2023-10-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_remainder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='remainder',
            new_name='reminder',
        ),
    ]
